<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>

    <AssemblyName>gamenyoi</AssemblyName>
    <RootNamespace>TJAPlayer3</RootNamespace>
    <ApplicationIcon>Gamenyoi.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Test\</OutputPath>
    <DefineConstants>TRACE;DEBUG;$(MyOption)</DefineConstants>
    <DebugType>full</DebugType>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\Test\</OutputPath>
    <DefineConstants>TRACE;$(MyOption)</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.2.1.24" />
    <PackageReference Include="LargeAddressAware" Version="1.0.6" />
    <PackageReference Include="Tomlyn" Version="0.17.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4" />
  </ItemGroup>
  <ItemGroup Label="Resources">
    <EmbeddedResource Include="Gamenyoi.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FDK19\FDK19.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Libs/**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="ThirdPartyLicenses/**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Songs/**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="System/**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Docs/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="../BannedSymbols.txt" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>gamenyoi</PackageId>
    <Version>1.8.2.1</Version>
    <Authors>Mr-Ojii</Authors>
    <NeutralLanguage>ja-JP</NeutralLanguage>
    <RepositoryUrl>https://github.com/Mr-Ojii/TJAPlayer3-f</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

</Project>
