name: build

on:
  push:
    branches:
      - master
    tags:
      - "Ver.*"

jobs:
  get_rev_list_count:
    name: Get rev-list_count
    runs-on: ubuntu-latest
    outputs:
      rev_list_count: ${{ steps.rev.outputs.REV_LIST_COUNT }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}
        REVCOUNT=`git rev-list --count HEAD`
        echo "REV_LIST_COUNT=${REVCOUNT}" >> $GITHUB_OUTPUT


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [get_rev_list_count]
    strategy:
      matrix:
        config:
          - { platform: win-x86,     os-platform: win }
          - { platform: win-x64,     os-platform: win }
          - { platform: osx-x64,     os-platform: osx }
          - { platform: osx-arm64,   os-platform: osx }
          - { platform: linux-x64,   os-platform: linux }
          - { platform: linux-arm64, os-platform: linux }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build
      run: dotnet publish gamenyoi -o publish -r ${{ matrix.config.platform }} -p:MyOption=PUBLISH -p:PublishSingleFile=true --configuration Release --self-contained true

    - name: Remove Folder
      run: |
        cd ${{ github.workspace }}/publish/Libs
        for filename in *
        do
          if [ ${filename} != ${{ matrix.config.platform }} && ${filename} != ${{ matrix.config.os-platform }} ] ; then
            rm -rf ${filename}
            echo ${filename}
          fi
        done

    - name: Rename App File (linux)
      if: ${{ matrix.config.os-platform == 'linux' }}
      run: |
        cd ${{ github.workspace }}
        mv "publish/gamenyoi" "publish/gamenyoi.AppImage"

    #Pre
    - name: Create Archive(Pre)
      if: (startsWith(github.ref, 'refs/tags/Ver')) != true
      run: |
        cd ${{ github.workspace }}
        zip "gamenyoi-PreRelease-${{ matrix.config.platform }}-${{ needs.get_rev_list_count.outputs.rev_list_count }}" -r publish

    - name: Upload Artifact(Pre)
      if: (startsWith(github.ref, 'refs/tags/Ver')) != true
      uses: actions/upload-artifact@v3
      with:
        name: gamenyoi
        path: ${{ github.workspace }}/gamenyoi-PreRelease-${{ matrix.config.platform }}-${{ needs.get_rev_list_count.outputs.rev_list_count }}.zip

    #Release
    - name: Create Archive
      if: (startsWith(github.ref, 'refs/tags/Ver'))
      run: |
        cd ${{ github.workspace }}
        zip "gamenyoi-${{ matrix.config.platform }}" -r publish

    - name: Upload Artifact
      if: (startsWith(github.ref, 'refs/tags/Ver'))
      uses: actions/upload-artifact@v3
      with:
        name: gamenyoi
        path: ${{ github.workspace }}/gamenyoi-${{ matrix.config.os-platform }}.zip


  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [get_rev_list_count, build]
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: gamenyoi
        path: artifacts

    # https://gist.github.com/superbrothers/af84a2f8af394a62352e06537a640746
    - name: Create a Release(Pre)
      if: (startsWith(github.ref, 'refs/tags/Ver')) != true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}/artifacts
        RELEASE_NAME=gamenyoi-prerelease-${{ needs.get_rev_list_count.outputs.rev_list_count }}
        TAG_NAME=prerelease-${{ needs.get_rev_list_count.outputs.rev_list_count }}
        gh release create "${TAG_NAME}" ${{ github.workspace }}/artifacts/*.zip -t "${RELEASE_NAME}" -p

    - name: Create a Release
      if: (startsWith(github.ref, 'refs/tags/Ver'))
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}/artifacts
        VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        RELEASE_NAME=${VERSION}
        TAG_NAME=${VERSION}
        gh release create "${TAG_NAME}" ${{ github.workspace }}/artifacts/*.zip -t "${RELEASE_NAME}"
